# General
server:
  port: 8761  # Standard Eureka server port

spring:
  application:
    name: igrp-eureka-server

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,env"
  endpoint:
    health:
      showDetails: always
      probes:
        enabled: true

# Eureka SERVER configuration
eureka:
  instance:
    hostname: ${HOSTNAME:eureka-server}  # Good for Kubernetes
    preferIpAddress: false  # Use hostname in K8s
  client:
    registerWithEureka: false  # Server doesn't register with itself
    fetchRegistry: false        # Server doesn't fetch from itself
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enableSelfPreservation: ${EUREKA_SELF_PRESERVATION:true}
    evictionIntervalTimerInMs: 15000
    renewalPercentThreshold: 0.85

# Logging configuration
logging:
  level:
    root: ${ROOT_LOG_LEVEL:INFO}
    cv.igrp.platform: INFO
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG