# General
server:
  port: 8761  # Standard Eureka server port

spring:
  application:
    name: igrp-eureka-server

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,env"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

# Eureka SERVER configuration
eureka:
  instance:
    hostname: ${HOSTNAME:eureka-server}  # Good for Kubernetes
    prefer-ip-address: false  # Use hostname in K8s
  client:
    register-with-eureka: false  # Server doesn't register with itself
    fetch-registry: false        # Server doesn't fetch from itself
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: ${EUREKA_SELF_PRESERVATION:true}
    eviction-interval-timer-in-ms: 15000
    renewal-percent-threshold: 0.85

# Logging configuration
logging:
  level:
    root: ${ROOT_LOG_LEVEL:INFO}
    cv.igrp.platform: INFO
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG